name: edaptia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_dotenv: ^5.2.1
  rename: ^3.1.0
  flutter_tts: ^4.2.3
  shared_preferences: ^2.2.2
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.4
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  cloud_firestore: ^6.1.0
  flutter_phoenix: ^1.1.1
  confetti: ^0.7.0
  flutter_markdown_plus: ^1.0.5
  share_plus: ^7.2.1
  google_sign_in: ^7.2.0
  device_info_plus: ^12.2.0
  package_info_plus: ^8.0.2
  posthog_flutter: ^4.3.3
  url_launcher: ^6.3.0
  firebase_remote_config: ^6.1.1
  firebase_data_connect: ^0.2.1
  flutter_riverpod: ^3.0.3
  fl_chart: ^0.66.2
  google_fonts: ^6.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk:  flutter  
  firebase_auth_mocks: ^0.15.1
  firebase_core_platform_interface: ^6.0.1
  flutter_lints: ^6.0.0
  mocktail: ^1.0.3
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/.env.public
    - env.public
    - assets/home/course.png
    - assets/home/language.png
    - assets/home/problem.png

runs-on: [self-hosted, windows]
